export const fakeData = [
  {
    label: "NIFTYIT",
    name: "Nifty IT",
    value: "38624.20",
    changeValue: "188.25",
    changePercent: "0.49",
    link: "/market/index/nse/niftyit",
  },
  {
    label: "NIFTYBANK",
    name: "Nifty Bank",
    value: "43210.15",
    changeValue: "254.60",
    changePercent: "0.59",
    link: "/market/index/nse/niftybank",
  },
  {
    label: "NIFTYFMCG",
    name: "Nifty FMCG",
    value: "44750.30",
    changeValue: "-78.40",
    changePercent: "-0.17",
    link: "/market/index/nse/niftyfmcg",
  },
  {
    label: "NIFTYMETAL",
    name: "Nifty Metal",
    value: "14520.65",
    changeValue: "112.45",
    changePercent: "0.78",
    link: "/market/index/nse/niftymetal",
  },
  {
    label: "NIFTYPHARMA",
    name: "Nifty Pharma",
    value: "13580.85",
    changeValue: "62.35",
    changePercent: "0.46",
    link: "/market/index/nse/niftypharma",
  },
];
