export const fakeStocks = [
  {
    symbol: "TCS",
    companyName: "Tata Consultancy Services",
    sector: "IT Services",
    marketCap: "12.5T",
    sharePrice: 3300.5,
    peRatio: 30.2,
    dividendYield: 1.2,
    popularProducts: ["TCS iON", "TCS BaNCS"],
    investors: ["BlackRock", "SBI Mutual Fund"],
    editable: false,
    tooltip: "Leading IT services company",
  },
  {
    symbol: "INFY",
    companyName: "Infosys Limited",
    sector: "IT Services",
    marketCap: "6.7T",
    sharePrice: 1500.75,
    peRatio: 28.5,
    dividendYield: 1.4,
    popularProducts: ["Infosys Finacle", "Infosys Nia"],
    investors: ["Vanguard", "HDFC Mutual Fund"],
    editable: false,
    tooltip: "Global leader in consulting and technology",
  },
  {
    symbol: "RELIANCE",
    companyName: "Reliance Industries Limited",
    sector: "Energy",
    marketCap: "18.3T",
    sharePrice: 2500.0,
    peRatio: 25.7,
    dividendYield: 0.8,
    popularProducts: ["Jio", "Reliance Petroleum"],
    investors: ["LIC", "ICICI Prudential"],
    editable: true,
    tooltip: "Diverse conglomerate with major energy interests",
  },
  {
    symbol: "HDFCBANK",
    companyName: "HDFC Bank Limited",
    sector: "Banking",
    marketCap: "8.4T",
    sharePrice: 1700.25,
    peRatio: 22.3,
    dividendYield: 1.1,
    popularProducts: ["HDFC Personal Loan", "HDFC Credit Card"],
    investors: ["HSBC", "Franklin Templeton"],
    editable: true,
    tooltip: "One of India's largest private sector banks",
  },
  {
    symbol: "ICICIBANK",
    companyName: "ICICI Bank Limited",
    sector: "Banking",
    marketCap: "6.0T",
    sharePrice: 900.85,
    peRatio: 20.5,
    dividendYield: 1.3,
    popularProducts: ["ICICI Home Loan", "ICICI Insurance"],
    investors: ["Morgan Stanley", "Tata Mutual Fund"],
    editable: true,
    tooltip: "Major player in banking and financial services",
  },
  {
    symbol: "HINDUNILVR",
    companyName: "Hindustan Unilever Limited",
    sector: "FMCG",
    marketCap: "7.1T",
    sharePrice: 2500.6,
    peRatio: 35.8,
    dividendYield: 1.5,
    popularProducts: ["Dove", "Lux"],
    investors: ["Aditya Birla Sun Life", "Aberdeen"],
    editable: true,
  },
  {
    symbol: "MARUTI",
    companyName: "Maruti Suzuki India Limited",
    sector: "Automobile",
    marketCap: "4.5T",
    sharePrice: 9500.75,
    peRatio: 29.1,
    dividendYield: 0.9,
    popularProducts: ["Alto", "Swift"],
    investors: ["Goldman Sachs", "Mirae Asset"],
    editable: true,
    tooltip: "Leading automobile manufacturer in India",
  },
  {
    symbol: "LTI",
    companyName: "L&T Infotech Limited",
    sector: "IT Services",
    marketCap: "3.2T",
    sharePrice: 4600.5,
    peRatio: 27.8,
    dividendYield: 1.0,
    popularProducts: ["LTI Canvas", "LTI Matrix"],
    investors: ["T Rowe Price", "Sundaram Mutual Fund"],
    editable: true,
    tooltip: "Specializes in IT services and solutions",
  },
  {
    symbol: "DRREDDY",
    companyName: "Dr. Reddy's Laboratories",
    sector: "Pharmaceuticals",
    marketCap: "2.8T",
    sharePrice: 4200.25,
    peRatio: 24.5,
    dividendYield: 1.2,
    popularProducts: ["Dolo", "Ciplox"],
    investors: ["JPMorgan Chase", "HDFC Life"],
    editable: false,
    tooltip: "Major pharmaceutical company in India",
  },
  {
    symbol: "BHARTIARTL",
    companyName: "Bharti Airtel Limited",
    sector: "Telecom",
    marketCap: "5.6T",
    sharePrice: 850.9,
    peRatio: 32.1,
    dividendYield: 1.1,
    popularProducts: ["Airtel Prepaid", "Airtel Postpaid"],
    investors: ["UBS", "Kotak Mutual Fund"],
    editable: true,
  },
  {
    symbol: "ADANIGREEN",
    companyName: "Adani Green Energy Limited",
    sector: "Renewable Energy",
    marketCap: "3.0T",
    sharePrice: 2200.4,
    peRatio: 42.5,
    dividendYield: 0.5,
    popularProducts: ["Solar Projects", "Wind Energy Solutions"],
    investors: ["Nomura", "ICICI Lombard"],
    editable: true,
    tooltip: "Focused on renewable energy solutions",
  },
  {
    symbol: "HCLTECH",
    companyName: "HCL Technologies Limited",
    sector: "IT Services",
    marketCap: "5.2T",
    sharePrice: 1200.75,
    peRatio: 26.3,
    dividendYield: 1.4,
    popularProducts: ["HCL Digital Transformation", "HCL Cloud Solutions"],
    investors: ["State Street", "L&T Mutual Fund"],
    editable: true,
    tooltip: "Provider of IT services and solutions",
  },
  {
    symbol: "UPL",
    companyName: "UPL Limited",
    sector: "Chemicals",
    marketCap: "2.3T",
    sharePrice: 850.65,
    peRatio: 19.2,
    dividendYield: 1.0,
    popularProducts: ["Herbicides", "Insecticides"],
    investors: ["HSBC Global Asset Management", "Edelweiss"],
    editable: false,
  },
  {
    symbol: "KOTAKBANK",
    companyName: "Kotak Mahindra Bank",
    sector: "Banking",
    marketCap: "4.8T",
    sharePrice: 2000.8,
    peRatio: 21.4,
    dividendYield: 1.2,
    popularProducts: ["Kotak Personal Loan", "Kotak Securities"],
    investors: ["Barclays", "Bajaj Allianz"],
    editable: true,
  },
  {
    symbol: "TATAMOTORS",
    companyName: "Tata Motors Limited",
    sector: "Automobile",
    marketCap: "1.9T",
    sharePrice: 350.3,
    peRatio: 17.5,
    dividendYield: 0.7,
    popularProducts: ["Tata Nano", "Tata Hexa"],
    investors: ["Morgan Stanley", "Principal Mutual Fund"],
    editable: false,
    tooltip: "Automobile manufacturer with diverse products",
  },
  {
    symbol: "ITC",
    companyName: "ITC Limited",
    sector: "FMCG",
    marketCap: "3.5T",
    sharePrice: 300.9,
    peRatio: 25.6,
    dividendYield: 2.5,
    popularProducts: ["Aashirvaad", "Sunfeast"],
    investors: ["HDFC", "Axis Mutual Fund"],
    editable: true,
  },
];
